version: '3.8'
services:
  db:
    container_name: juliet-user-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=examplesys
    ports:
      - '5432:5432'
    volumes:
      - ./dev-db:/var/lib/postgresql/data
